Repository OKTW-Network/Galaxy, pull requests merged in 2018-07, with the labels that each got.

#94 Fix galaxy manage GUI and traveler save
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#95 Fix player data save and command spawn not safe
  src/main/kotlin/one/oktw/galaxy/command/Spawn.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#96 Check have galaxy on create galaxy
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
Labels: bug

#99 Try fix player inventory loss
  src/main/kotlin/one/oktw/galaxy/galaxy/GalaxyManager.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#100 fix again player data save
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#102 Fix load player data cause item loss
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#104 Right click harvest
  src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt
  src/main/kotlin/one/oktw/galaxy/player/event/Harvest.kt
Labels: enhancement

#106 Fix viewer
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#105 Elevator
  src/main/kotlin/one/oktw/galaxy/block/enums/CustomBlocks.kt
  src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt
  src/main/kotlin/one/oktw/galaxy/economy/service/EconomyService.kt
  src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt
  src/main/kotlin/one/oktw/galaxy/internal/register/RecipeRegister.kt
  src/main/kotlin/one/oktw/galaxy/player/event/Elevator.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: enhancement

#101 fix GUI helper thread safe
  src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt
Labels: bug, need testing

#108 Only cancel armor item on ChangeInventoryEvent
  src/main/kotlin/one/oktw/galaxy/armor/event/Armor.kt
  src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt
  src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt
Labels: bug

#110 Skip unbreakable custom block
  src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
Labels: bug

#111 修正加入申請
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#112 修正瀏覽介面
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
Labels: bug

#113 跳過儲存訪客模式玩家
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#114 確保關閉伺服器時儲存所有資料
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#116 Remove viewer after disconnect event
  src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
Labels: bug

#117 Fix custom block replace exist block
  src/main/kotlin/one/oktw/galaxy/block/event/FakeBlock.kt
Labels: bug, need to test

#120 Fix load save traveler
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#119 Fix gun not saved
  src/main/kotlin/one/oktw/galaxy/command/admin/Gun.kt
Labels: bug

#123 修正裝備可以拿下來
  src/main/kotlin/one/oktw/galaxy/armor/event/Armor.kt
  src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt
  src/main/kotlin/one/oktw/galaxy/economy/event/TravelerEvent.kt
  src/main/kotlin/one/oktw/galaxy/internal/register/EventRegister.kt
Labels: bug

#121 fix not clean exp
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt
Labels: bug

#124 Change elevator teleport limit to 16 blocks
  src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
Labels: bug, enhancement

#125 fix beetroots can not right click harvest
  src/main/kotlin/one/oktw/galaxy/player/event/Harvest.kt
Labels: bug

#127 Fix GUI button and memory leak
  src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
Labels: bug

#128 Refacetor mongodb async
  build.gradle
  src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt
  src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyInfo.kt
  src/main/kotlin/one/oktw/galaxy/command/admin/GalaxyManage.kt
  src/main/kotlin/one/oktw/galaxy/command/admin/Gun.kt
  src/main/kotlin/one/oktw/galaxy/command/admin/PlayerInfo.kt
  src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt
  src/main/kotlin/one/oktw/galaxy/economy/service/EconomyService.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/GalaxyManager.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/data/extensions/Galaxy.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/TeleportHelper.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/data/extensions/Planet.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/populator/Spawn.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
  src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
  src/main/kotlin/one/oktw/galaxy/internal/DatabaseManager.kt
  src/main/kotlin/one/oktw/galaxy/internal/register/DataRegister.kt
  src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: need to test

#130 Show total star dusts a player have when got a new one
  src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: enhancement, need to test

#132 Performance
  src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
  src/main/kotlin/one/oktw/galaxy/item/event/ItemProtect.kt
  src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
Labels: need to test

#134 Fix actionbar thread safe
  src/main/kotlin/one/oktw/galaxy/command/Spawn.kt
  src/main/kotlin/one/oktw/galaxy/economy/event/EconomyEvent.kt
  src/main/kotlin/one/oktw/galaxy/item/service/CoolDown.kt
  src/main/kotlin/one/oktw/galaxy/player/service/ActionBar.kt
Labels: bug

#136 Number select
  src/main/kotlin/one/oktw/galaxy/gui/GUIHelper.kt
  src/main/kotlin/one/oktw/galaxy/gui/NumberSelect.kt
  src/main/kotlin/one/oktw/galaxy/item/enums/ButtonType.kt
  src/main/kotlin/one/oktw/galaxy/item/type/Button.kt
Labels: GUI, enhancement

#140 change ui key
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/Confirm.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyInfo.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt
  src/main/kotlin/one/oktw/galaxy/gui/GroupSelect.kt
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
  src/main/kotlin/one/oktw/galaxy/gui/ManageMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
  src/main/kotlin/one/oktw/galaxy/gui/UpgradeSlot.kt
  src/main/kotlin/one/oktw/galaxy/gui/machine/ChunkLoader.kt
  src/main/kotlin/one/oktw/galaxy/gui/machine/PlanetTerminal.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: need to test

#138 Rewrite PlanetTerminal
  src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt
  src/main/kotlin/one/oktw/galaxy/gui/NumberSelect.kt
  src/main/kotlin/one/oktw/galaxy/gui/machine/PlanetTerminal.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: GUI, enhancement, need to test

#139 刪除星系成員立即將在該星系星球內的被移除玩家設為訪客模式
  src/main/kotlin/one/oktw/galaxy/galaxy/data/extensions/Galaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/ManageMember.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: need to test

#146 Fix ChunkLoader POJO
  src/main/kotlin/one/oktw/galaxy/machine/chunkloader/data/ChunkLoader.kt
Labels: bug

#151 Chat input and confirm
  src/main/kotlin/one/oktw/galaxy/util/Chat.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
Labels: GUI, enhancement, need to test

#133 Add gui view generator for better writing gui and a helper class to launch job in sequence
  src/main/kotlin/one/oktw/galaxy/gui/view/GUIView.kt
  src/main/kotlin/one/oktw/galaxy/gui/view/GridGUIView.kt
  src/main/kotlin/one/oktw/galaxy/util/OrderedLaunch.kt
Labels: need to test

#154 Planet type
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/data/Planet.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/enums/PlanetType.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
  src/main/kotlin/one/oktw/galaxy/item/enums/ButtonType.kt
Labels: GUI, enhancement

#155 Fix swich planet
  src/main/kotlin/one/oktw/galaxy/player/event/PlayerControl.kt
Labels: bug

#157 Fix chunk loader position
  src/main/kotlin/one/oktw/galaxy/gui/machine/ChunkLoader.kt
  src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoader.kt
  src/main/kotlin/one/oktw/galaxy/machine/chunkloader/ChunkLoaderManager.kt
Labels: status: ready to merge, type: bug

#153 Impl input
  src/main/kotlin/one/oktw/galaxy/extensions/Text.kt
  src/main/kotlin/one/oktw/galaxy/gui/AddMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/CreateGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/CreatePlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyInfo.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
  src/main/kotlin/one/oktw/galaxy/gui/RenameGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/util/Chat.kt
Labels: status: ready to merge, system: GUI, type: enhancement

#162 Add text to show GalaxyManagement
  src/main/kotlin/one/oktw/galaxy/gui/MainMenu.kt
Labels: status: needs review, system: GUI, type: enhancement

#161 Pre galaxy ender chest
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/TravelerHelper.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/traveler/data/Traveler.kt
Labels: status: ready to merge, system: galaxy

#158 Fix PageGUI and prevent user from change page too fast
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
Labels: type: bug

#156 Nether
  .circleci/config.yml
  build.gradle
  src/main/java/one/oktw/galaxy/mixin/MixinBiomeProviderSingle.java
  src/main/java/one/oktw/galaxy/mixin/MixinWorldProviderHell.java
  src/main/kotlin/one/oktw/galaxy/Main.kt
  src/main/kotlin/one/oktw/galaxy/block/event/BlockGUI.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/data/extensions/Galaxy.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/PlanetHelper.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/TeleportHelper.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/NetherGenModifier.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/NormalGenModifier.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/populator/Spawn.kt
  src/main/kotlin/one/oktw/galaxy/galaxy/planet/gen/populator/SpawnPosFix.kt
  src/main/kotlin/one/oktw/galaxy/gui/CreatePlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyManagement.kt
  src/main/resources/assets/galaxy/lang/en-US.cfg
  src/main/resources/assets/galaxy/lang/zh-TW.cfg
  src/main/resources/mixins.galaxy.json
Labels: status: needs review, status: needs testing, system: GUI, system: galaxy, type: enhancement

#165 Fix mixin refmap gen
  .circleci/config.yml
  .travis.yml
  build.gradle
Labels: type: bug

#163 Add page number
  src/main/kotlin/one/oktw/galaxy/gui/BrowserGalaxy.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserMember.kt
  src/main/kotlin/one/oktw/galaxy/gui/BrowserPlanet.kt
  src/main/kotlin/one/oktw/galaxy/gui/GalaxyJoinRequest.kt
  src/main/kotlin/one/oktw/galaxy/gui/PageGUI.kt
Labels: status: needs testing, system: GUI, type: enhancement

#164 performance
  src/main/kotlin/one/oktw/galaxy/block/event/Elevator.kt
  src/main/kotlin/one/oktw/galaxy/item/event/ItemProtect.kt
  src/main/kotlin/one/oktw/galaxy/player/event/Viewer.kt
Labels: status: needs testing, type: performance

#167 Fix some vanilla performance issue
  build.gradle
  src/main/java/one/oktw/galaxy/mixin/MixinCommandBase.java
  src/main/java/one/oktw/galaxy/mixin/MixinWorldProviderHell.java
  src/main/java/one/oktw/galaxy/mixin/MixinWorldServer.java
  src/main/resources/mixins.galaxy.json
Labels: status: needs review, status: needs testing, type: performance
