Repository OKTW-Network/Galaxy, pull requests merged in 2018-09, with the labels that each got.

#200 update minecraft mapping to stable_39
  build.gradle
  src/main/kotlin/one/oktw/galaxy/Main.kt
Labels: status: ready to merge

#192 add more button type
  src/main/kotlin/one/oktw/galaxy/item/enums/ButtonType.kt
Labels: status: needs testing, system: GUI

#174 Add smelting recipe
  src/main/kotlin/one/oktw/galaxy/internal/register/RecipeRegister.kt
  src/main/kotlin/one/oktw/galaxy/util/extensions/Ingredient.kt
Labels: status: needs testing
