Repository OKTW-Network/Galaxy, pull requests merged in 2019-02, with the labels that each got.

#234 Fix issue 232
  src/main/kotlin/one/oktw/galaxy/gui/machine/Teleporter.kt
  src/main/kotlin/one/oktw/galaxy/machine/teleporter/TeleporterHelper.kt
Labels: status: needs review, status: needs testing, system: galaxy, type: bug

#236 minimize jar
  build.gradle
Labels: status: needs testing

#222 More EZ Recipe
  src/main/kotlin/one/oktw/galaxy/internal/register/EasyRecipeRegister.kt
Labels: status: needs review, system: item, type: enhancement

#239 Filter metadata files
  build.gradle
Labels: status: needs testing

#240 Remove unused bug fix
  src/main/java/one/oktw/galaxy/mixin/MixinWorldServer.java
  src/main/resources/mixins.galaxy.json
Labels: status: ready to merge, type: bug
