Repository OKTW-Network/Galaxy, pull requests merged in 2020-01, with the labels that each got.

#282 Workaround harvest bugs
  build.gradle.kts
  src/main/java/one/oktw/galaxy/mixin/event/MixinItem_Item.java
  src/main/java/one/oktw/galaxy/mixin/event/MixinPlayerInteractItem_NetworkHandler.java
  src/main/java/one/oktw/galaxy/network/ItemFunctionAccessor.java
  src/main/kotlin/one/oktw/galaxy/event/type/PlayerInteractItemEvent.kt
  src/main/kotlin/one/oktw/galaxy/player/Harvest.kt
  src/main/resources/galaxy.mixin.json
Labels: status: needs review, status: needs testing, type: bug

#288 Add itemType Data To Item
  src/main/kotlin/one/oktw/galaxy/item/Button.kt
  src/main/kotlin/one/oktw/galaxy/item/Gui.kt
  src/main/kotlin/one/oktw/galaxy/item/Material.kt
  src/main/kotlin/one/oktw/galaxy/item/Tool.kt
  src/main/kotlin/one/oktw/galaxy/item/Upgrade.kt
  src/main/kotlin/one/oktw/galaxy/item/Weapon.kt
  src/main/kotlin/one/oktw/galaxy/item/util/CustomItemBuilder.kt
Labels: status: needs review, status: needs testing, system: item

#290 Add fabric cache in Travis CI, CircleCI and GitHub Actions
  .circleci/config.yml
  .github/workflows/workflow.yml
  .travis.yml
Labels: status: needs review, status: needs testing, type: performance

#280 Realtime patch
  src/main/java/org/spongepowered/common/bridge/RealTimeTrackingBridge.java
  src/main/java/org/spongepowered/common/mixin/realtime/blockentity/AbstractFurnaceBlockEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/blockentity/BrewingStandBlockEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/EntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/ExperienceOrbEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/ItemEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/LivingEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/CreeperEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/MobEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/mob/ZombieVillagerEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/passive/PassiveEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/player/ItemCooldownManagerMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/entity/player/PlayerEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/server/MinecraftServerMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayNetworkHandlerMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayerEntityMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/server/network/ServerPlayerInteractionManagerMixin_RealTime.java
  src/main/java/org/spongepowered/common/mixin/realtime/world/WorldMixin_RealTime.java
  src/main/resources/fabric.mod.json
  src/main/resources/sponge.realtime.mixin.json
Labels: status: needs review, status: needs testing, type: performance
